train_path: data/Q1/training
val_path: data/Q1/validation
dataset: Q1

wandb: True
num_of_workers: 32
batch_size: 20
epochs: 100
val_check_interval: 1.0
precision: 16
gpu: 2

dataset_train:
  total_variables:
  total_coefficients:
  max_number_of_points: 10000
  number_of_sets: 10
  lambda_: 0.5
  type_of_sampling_points: constant
  predict_c: True
  fun_support:
    max: 10
    min: -10
  constants:
    num_constants: 5
    additive:
      max: 5
      min: -5
    multiplicative:
      max: 5
      min: -5

dataset_val:
  total_variables: #Do not fill
  total_coefficients: #Do not fill
  max_number_of_points: 5000
  number_of_sets: 10
  type_of_sampling_points: constant
  predict_c: True
  fun_support:
    max: 10
    min: -10
  constants:
    num_constants: 5
    additive:
      max: 5
      min: -5
    multiplicative:
      max: 5
      min: -5

dataset_test:
  total_variables: #Do not fill
  total_coefficients: #Do not fill
  max_number_of_points: 500
  number_of_sets: 10
  type_of_sampling_points: constant
  predict_c: False
  fun_support:
    max: 10
    min: -10
  constants:
    num_constants: 5
    additive:
      max: 5
      min: -5
    multiplicative:
      max: 5
      min: -5

architecture:
  block_size: 3000
  sinuisodal_embeddings: False
  dec_pf_dim: 512
  dec_layers: 5
  dim_hidden: 480 #420
  lr: 0.0001
  dropout: 0
  num_features: 5  # 10
  ln: True
  N_p: 0
  num_inds: 50
  activation: "relu"
  bit16: True
  norm: True
  linear: False
  input_normalization: False
  src_pad_idx: 0
  trg_pad_idx: 0
  length_eq: 40
  n_l_enc: 5
  mean: 0.5
  std: 0.5
  dim_input: 2
  num_heads: 16 # 16
  output_dim: 32
  number_of_sets: 10
  num_tokens_condition: 32
  embedding_dim_condition: 480
  cond_num_layers: 3

inference:
  beam_size: 5
  bfgs:
    activated: True
    n_restarts: 10
    add_coefficients_if_not_existing: False
    normalization_o: False
    idx_remove: True
    normalization_type: MSE
    stop_time: 1e9

# @package _group_
hydra:
  run:
    dir: run/${dataset_train.predict_c}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
      dir: runs/${dataset_train.predict_c}/${now:%Y-%m-%d}/${now:%H-%M-%S}